# HTTP Server (Tomcat) Port
server:
#  port: 3333
  error:
    whitelabel:
      enabled: true

spring:
#  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_YSD_SERVICE_HOST}:${MYSQL_YSD_SERVICE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver

    #    url: jdbc:mysql://localhost:3306/ysd_db?user=jim&password=0000&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#---
#    url: jdbc:mysql://localhost:3306/ysd_db?useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: root
#---
#    url: ${vcap.services.cupsdb01.credentials.url}?useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: ${vcap.services.cupsdb01.credentials.user}
#    password: ${vcap.services.cupsdb01.credentials.password}
#---
#    url: jdbc:mysql://q-n1s3y1.q-g167.bosh:3306/service_instance_db
#    username: dad54a75d84a4b4c81fd06c9609d391a
#    password: t78v6ueio6gr2dc5
#---
#    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      max-active: 5
      max-idle: 5
      min-idle: 5
      initial-size: 5
    hikari:
      connection-timeout: 3000
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 5
      validation-timeout: 1000

#MANAGEMENT_SECURITY_ENABLED: false
#WELCOME_MESSAGE: Hello from the review environment

#logging.level:
#  root: WARN
#  org.superbiz.moviefun: DEBUG
#
#s3:
#  accessKey: <access key id>
#  secretKey: <secret access key>
#  bucketName: <name of the bucket>

#WELCOME_MESSAGE: Hello from the review environment
#MANAGEMENT_SECURITY_ENABLED: false

#spring.redis:
#  host: localhost
#  port: 6379
#  password: null
#  database: 0
#  pool:
#    max-idle: 8
#    min-idle: 0
#    max-active: 8
#    max-wait: -1
