# HTTP Server (Tomcat) Port
server:
  port: 3333
  error:
    whitelabel:
      enabled: true

spring:
#  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
#    url: jdbc:mysql://localhost:3306/ysd_db?user=jim&password=0000&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://localhost:3306/ysd_db?useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
#    url: ${vcap.services.my-user-provided-service.credentials.url}
#    username: ${vcap.services.my-user-provided-service.credentials.user}
#    password: ${vcap.services.my-user-provided-service.credentials.password}
    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      max-active: 5
      max-idle: 5
      min-idle: 5
      initial-size: 5
    hikari:
      connection-timeout: 3000
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 5
      validation-timeout: 1000

#MANAGEMENT_SECURITY_ENABLED: false
#WELCOME_MESSAGE: Hello from the review environment

#logging.level:
#  root: WARN
#  org.superbiz.moviefun: DEBUG
#
#s3:
#  accessKey: <access key id>
#  secretKey: <secret access key>
#  bucketName: <name of the bucket>

#WELCOME_MESSAGE: Hello from the review environment
#MANAGEMENT_SECURITY_ENABLED: false
