package io.pivotal.pal.tracker;
// Generated 2018/12/06 11:25:22 by Hibernate Tools 3.2.0.b11


import java.sql.Date;

//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.Id;
//import javax.persistence.Table;

/**
 * Invoice generated by hbm2java
 */
//@Entity
//@Table(name="invoice")
public class Invoice  implements java.io.Serializable {

//    @Id
//    @Column(name="invoiceNumber")
    private Integer invoiceNumber;

//    @Column(name="caryOnOrCargoBooking")
    private String caryOnOrCargoBooking;

//    @Column(name="settlement")
    private String settlement;

//    @Column(name="size")
    private Integer size;

//    @Column(name="charge")
    private Integer charge;

//    @Column(name="flightCode")
    private String flightCode;

//    @Column(name="customerCode")
    private String customerCode;

//    @Column(name="dealer")
    private String dealer;

//    @Column(name="personInCharge")
    private String personInCharge;

//    @Column(name="receiptDate")
    private Date receiptDate;

//    @Column(name="deliveryDate")
    private Date deliveryDate;

//    @Column(name="receiptVoucher")
    private String receiptVoucher;

//    @Column(name="invoiceType")
    private String invoiceType;

//    @Column(name="address")
    private String address;

//    @Column(name="goods")
    private String goods;

//    @Column(name="client")
    private String client;

//    @Column(name="requestDate")
    private Date requestDate;

//    @Column(name="fullName")
    private String fullName;

//    @Column(name="postalCode")
    private String postalCode;

//    @Column(name="telephoneNumber")
    private String telephoneNumber;

//    @Column(name="destination")
    private String destination;

//    @Column(name="position")
    private String position;

//    @Column(name="goodsCode")
    private String goodsCode;

//    @Column(name="goodsName")
    private String goodsName;

//    @Column(name="pickup")
    private String pickup;

//    @Column(name="GolfOrSkiOrAirport")
    private String GolfOrSkiOrAirport;

//    @Column(name="clubNumber")
    private String clubNumber;

//    @Column(name="service")
    private String service;

    public Invoice() {
    }


    public Invoice(Integer invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    public Invoice(Integer invoiceNumber, String caryOnOrCargoBooking, String settlement, Integer size, Integer charge, String flightCode, String customerCode, String dealer, String personInCharge, Date receiptDate, Date deliveryDate, String receiptVoucher, String invoiceType, String address, String goods, String client, Date requestDate, String fullName, String postalCode, String telephoneNumber, String destination, String position, String goodsCode, String goodsName, String pickup, String GolfOrSkiOrAirport, String clubNumber, String service) {
        this.invoiceNumber = invoiceNumber;
        this.caryOnOrCargoBooking = caryOnOrCargoBooking;
        this.settlement = settlement;
        this.size = size;
        this.charge = charge;
        this.flightCode = flightCode;
        this.customerCode = customerCode;
        this.dealer = dealer;
        this.personInCharge = personInCharge;
        this.receiptDate = receiptDate;
        this.deliveryDate = deliveryDate;
        this.receiptVoucher = receiptVoucher;
        this.invoiceType = invoiceType;
        this.address = address;
        this.goods = goods;
        this.client = client;
        this.requestDate = requestDate;
        this.fullName = fullName;
        this.postalCode = postalCode;
        this.telephoneNumber = telephoneNumber;
        this.destination = destination;
        this.position = position;
        this.goodsCode = goodsCode;
        this.goodsName = goodsName;
        this.pickup = pickup;
        this.GolfOrSkiOrAirport = GolfOrSkiOrAirport;
        this.clubNumber = clubNumber;
        this.service = service;
    }

    public Integer getInvoiceNumber() {
        return this.invoiceNumber;
    }

    public void setInvoiceNumber(Integer invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    public String getCaryOnOrCargoBooking() {
        return this.caryOnOrCargoBooking;
    }

    public void setCaryOnOrCargoBooking(String caryOnOrCargoBooking) {
        this.caryOnOrCargoBooking = caryOnOrCargoBooking;
    }
    public String getSettlement() {
        return this.settlement;
    }

    public void setSettlement(String settlement) {
        this.settlement = settlement;
    }
    public Integer getSize() {
        return this.size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }
    public Integer getCharge() {
        return this.charge;
    }

    public void setCharge(Integer charge) {
        this.charge = charge;
    }
    public String getFlightCode() {
        return this.flightCode;
    }

    public void setFlightCode(String flightCode) {
        this.flightCode = flightCode;
    }
    public String getCustomerCode() {
        return this.customerCode;
    }

    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }
    public String getDealer() {
        return this.dealer;
    }

    public void setDealer(String dealer) {
        this.dealer = dealer;
    }
    public String getPersonInCharge() {
        return this.personInCharge;
    }

    public void setPersonInCharge(String personInCharge) {
        this.personInCharge = personInCharge;
    }
    public Date getReceiptDate() {
        return this.receiptDate;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getReceiptVoucher() {
        return this.receiptVoucher;
    }

    public void setReceiptVoucher(String receiptVoucher) {
        this.receiptVoucher = receiptVoucher;
    }
    public String getInvoiceType() {
        return this.invoiceType;
    }

    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    public String getGoods() {
        return this.goods;
    }

    public void setGoods(String goods) {
        this.goods = goods;
    }
    public String getClient() {
        return this.client;
    }

    public void setClient(String client) {
        this.client = client;
    }
    public Date getRequestDate() {
        return this.requestDate;
    }

    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getTelephoneNumber() {
        return this.telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }
    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }
    public String getGoodsCode() {
        return this.goodsCode;
    }

    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }
    public String getGoodsName() {
        return this.goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }
    public String getPickup() {
        return this.pickup;
    }

    public void setPickup(String pickup) {
        this.pickup = pickup;
    }
    public String getGolfOrSkiOrAirport() {
        return this.GolfOrSkiOrAirport;
    }

    public void setGolfOrSkiOrAirport(String GolfOrSkiOrAirport) {
        this.GolfOrSkiOrAirport = GolfOrSkiOrAirport;
    }
    public String getClubNumber() {
        return this.clubNumber;
    }

    public void setClubNumber(String clubNumber) {
        this.clubNumber = clubNumber;
    }
    public String getService() {
        return this.service;
    }

    public void setService(String service) {
        this.service = service;
    }
}